# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dakre/dpr_rt/hw/Sources/lab/jtag_axi_ctrl/jtag_axi_ctrl.xci
# IP: The module: 'jtag_axi_ctrl' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/jtag_axi_ctrl/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_ctrl'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/jtag_axi_ctrl/jtag_axi_ctrl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/dakre/dpr_rt/hw/Sources/lab/jtag_axi_ctrl/jtag_axi_ctrl.xci
# IP: The module: 'jtag_axi_ctrl' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/jtag_axi_ctrl/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/jtag_axi_ctrl/jtag_axi_ctrl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
