# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dakre/dpr_rt/hw/Sources/lab/axi_rtl/axi_rtl.xci
# IP: The module: 'axi_rtl' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/axi_rtl/axi_rtl_impl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_rtl'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/axi_rtl/axi_rtl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_rtl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/axi_rtl/axi_rtl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_rtl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/dakre/dpr_rt/hw/Sources/lab/axi_rtl/axi_rtl.xci
# IP: The module: 'axi_rtl' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/axi_rtl/axi_rtl_impl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_rtl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/axi_rtl/axi_rtl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_rtl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/axi_rtl/axi_rtl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_rtl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
