# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dakre/dpr_rt/hw/Sources/lab/processing_system7_0/processing_system7_0.xci
# IP: The module: 'processing_system7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/processing_system7_0/processing_system7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system7_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/dakre/dpr_rt/hw/Sources/lab/processing_system7_0/processing_system7_0.xci
# IP: The module: 'processing_system7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/processing_system7_0/processing_system7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
