
####################################################################################
# Generated by Vivado 2017.4 built on 'Fri Dec 15 20:54:30 MST 2017' by 'xbuild'
# Command Used: write_xdc -force ./Sources/xdc/top_all_nrt.xdc
####################################################################################


####################################################################################
# Constraints from file : 'axi_em_ctrl_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------




####################################################################################
# Constraints from file : 'axi_em_ctrl.xdc'
####################################################################################


# (c) Copyright 2009 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.

current_instance axi_em_ctrl_1
set_property IOB TRUE [get_cells {U0/EMC_CTRL_I/IO_REGISTERS_I/Mem_DQ_I_v_reg[*]}]
set_property IOB TRUE [get_cells {U0/EMC_CTRL_I/IO_REGISTERS_I/mem_dq_o_reg_reg[*]}]
set_property IOB TRUE [get_cells {U0/EMC_CTRL_I/IO_REGISTERS_I/mem_cen_reg_reg[*]}]

set_property IOB TRUE [get_cells {U0/EMC_CTRL_I/IO_REGISTERS_I/mem_dq_t_reg_reg[*]}]




####################################################################################
# Constraints from file : 'prc.xdc'
####################################################################################


#  (c) Copyright 2015-2017 Xilinx, Inc. All rights reserved.
#
#  This file contains confidential and proprietary information
#  of Xilinx, Inc. and is protected under U.S. and
#  international copyright and other intellectual property
#  laws.
#
#  DISCLAIMER
#  This disclaimer is not a license and does not grant any
#  rights to the materials distributed herewith. Except as
#  otherwise provided in a valid license issued to you by
#  Xilinx, and to the maximum extent permitted by applicable
#  law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
#  WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
#  AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
#  BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
#  INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
#  (2) Xilinx shall not be liable (whether in contract or tort,
#  including negligence, or under any other theory of
#  liability) for any loss or damage of any kind or nature
#  related to, arising under or in connection with these
#  materials, including for any direct, or any indirect,
#  special, incidental, or consequential loss or damage
#  (including loss of data, profits, goodwill, or any type of
#  loss or damage suffered as a result of any action brought
#  by a third party) even if such damage or loss was
#  reasonably foreseeable or Xilinx had been advised of the
#  possibility of the same.
#
#  CRITICAL APPLICATIONS
#  Xilinx products are not designed or intended to be fail-
#  safe, or for use in any application requiring fail-safe
#  performance, such as life-support or safety devices or
#  systems, Class III medical devices, nuclear facilities,
#  applications related to the deployment of airbags, or any
#  other applications that could lead to death, personal
#  injury, or severe property or environmental damage
#  (individually and collectively, "Critical
#  Applications"). Customer assumes the sole risk and
#  liability of any use of Xilinx products in Critical
#  Applications, subject only to applicable laws and
#  regulations governing limitations on product liability.
#
#  THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
#  PART OF THIS FILE AT ALL TIMES.
# --------------------------------------------------------------------------

#-----------------------------------
# CDC Synchroniser constraints
#-----------------------------------
current_instance -quiet
current_instance prc_1/U0
set_false_path -to [get_pins -hier *cdc_to*/D]



####################################################################################
# Constraints from file : 'top_io.xdc'
####################################################################################


####################################################################################
# Generated by Vivado 2017.4 built on 'Fri Dec 15 20:54:30 MST 2017' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'design_1_processing_system7_0_0.xdc'
####################################################################################

############################################################################
##
##  Xilinx, Inc. 2006            www.xilinx.com
############################################################################
##  File name :       ps7_constraints.xdc
##
##  Details :     Constraints file
##                    FPGA family:       zynq
##                    FPGA:              xc7z020clg400-1
##                    Device Size:        xc7z020
##                    Package:            clg400
##                    Speedgrade:         -1
##
##
############################################################################
############################################################################
############################################################################
# Clock constraints                                                        #
############################################################################
#The clocks are asynchronous, user should constrain them appropriately.#


############################################################################
# I/O STANDARDS and Location Constraints                                   #
############################################################################

#  Enet 0 / mdio / MIO[53]
#  Enet 0 / mdc / MIO[52]
#  GPIO / gpio[51] / MIO[51]
#  GPIO / gpio[50] / MIO[50]
#  UART 1 / rx / MIO[49]
#  UART 1 / tx / MIO[48]
#  SD 0 / cd / MIO[47]
#  USB Reset / reset / MIO[46]
#  SD 0 / data[3] / MIO[45]
#  SD 0 / data[2] / MIO[44]
#  SD 0 / data[1] / MIO[43]
#  SD 0 / data[0] / MIO[42]
#  SD 0 / cmd / MIO[41]
#  SD 0 / clk / MIO[40]
#  USB 0 / data[7] / MIO[39]
#  USB 0 / data[6] / MIO[38]
#  USB 0 / data[5] / MIO[37]
#  USB 0 / clk / MIO[36]
#  USB 0 / data[3] / MIO[35]
#  USB 0 / data[2] / MIO[34]
#  USB 0 / data[1] / MIO[33]
#  USB 0 / data[0] / MIO[32]
#  USB 0 / nxt / MIO[31]
#  USB 0 / stp / MIO[30]
#  USB 0 / dir / MIO[29]
#  USB 0 / data[4] / MIO[28]
#  Enet 0 / rx_ctl / MIO[27]
#  Enet 0 / rxd[3] / MIO[26]
#  Enet 0 / rxd[2] / MIO[25]
#  Enet 0 / rxd[1] / MIO[24]
#  Enet 0 / rxd[0] / MIO[23]
#  Enet 0 / rx_clk / MIO[22]
#  Enet 0 / tx_ctl / MIO[21]
#  Enet 0 / txd[3] / MIO[20]
#  Enet 0 / txd[2] / MIO[19]
#  Enet 0 / txd[1] / MIO[18]
#  Enet 0 / txd[0] / MIO[17]
#  Enet 0 / tx_clk / MIO[16]
#  GPIO / gpio[15] / MIO[15]
#  GPIO / gpio[14] / MIO[14]
#  GPIO / gpio[13] / MIO[13]
#  GPIO / gpio[12] / MIO[12]
#  GPIO / gpio[11] / MIO[11]
#  GPIO / gpio[10] / MIO[10]
#  GPIO / gpio[9] / MIO[9]
#  Quad SPI Flash / qspi_fbclk / MIO[8]
#  GPIO / gpio[7] / MIO[7]
#  Quad SPI Flash / qspi0_sclk / MIO[6]
#  Quad SPI Flash / qspi0_io[3]/HOLD_B / MIO[5]
#  Quad SPI Flash / qspi0_io[2] / MIO[4]
#  Quad SPI Flash / qspi0_io[1] / MIO[3]
#  Quad SPI Flash / qspi0_io[0] / MIO[2]
#  Quad SPI Flash / qspi0_ss_b / MIO[1]
#  GPIO / gpio[0] / MIO[0]






# Customization
current_instance -quiet
set_property IOSTANDARD LVCMOS33 [get_ports comp_eq]
set_property IOSTANDARD LVCMOS33 [get_ports comp_gt]
set_property IOSTANDARD LVCMOS33 [get_ports comp_lt]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op_sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_o[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {icap_i[31]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports icap_reset]
set_property IOSTANDARD LVCMOS33 [get_ports mux_sel]
set_property IOSTANDARD LVCMOS33 [get_ports rst]


####################################################################################
# Constraints from file : 'xpm_cdc_gray.tcl'
####################################################################################

# Scoped constraints for xpm_cdc_gray





# Scoped constraints for xpm_cdc_gray





# Scoped constraints for xpm_cdc_gray





# Scoped constraints for xpm_cdc_gray






####################################################################################
# Constraints from file : 'xpm_cdc_sync_rst.tcl'
####################################################################################

# Scoped constraints for xpm_cdc_srst
current_instance prc_1/U0/i_cp0/i_bs_fifo/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.rrst_wr_inst
set_false_path -to [get_cells {syncstages_ff_reg[0]}]


# Scoped constraints for xpm_cdc_srst
current_instance -quiet
current_instance prc_1/U0/i_cp0/i_bs_fifo/gnuram_async_fifo.xpm_fifo_base_inst/xpm_fifo_rst_inst/gen_rst_ic.wrst_rd_inst
set_false_path -to [get_cells {syncstages_ff_reg[0]}]



####################################################################################
# Constraints from file : 'xpm_fifo_rst.tcl'
####################################################################################

# Scoped constraints for xpm_fifo
#if {([llength [ get_cells -hier *src_gray_ff_reg* -quiet]] > 0)} {
#set_false_path -from [get_pins -hierarchical -filter {NAME =~ *wr_rst_i_reg/C}] -to [get_pins -hierarchical -filter {NAME =~ *d_out_reg/D}]
#wr_rst_rd_reg[*]/D}]
#set_false_path -from [get_pins -hierarchical -filter {NAME =~ *rd_rst_d3_reg/C}] -to [get_pins -hierarchical -filter {NAME =~ *d_out_reg/D}]
#}

current_instance -quiet
current_instance prc_1/U0/i_cp0/i_bs_fifo/gnuram_async_fifo.xpm_fifo_base_inst
set_false_path -from [filter [all_fanout -from [get_ports -scoped_to_current_instance wr_clk] -flat -endpoints_only] IS_LEAF] -through [get_pins -of_obj [get_cells -hier * -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==drom}] -filter DIRECTION==OUT]


# Scoped constraints for xpm_fifo
#if {([llength [ get_cells -hier *src_gray_ff_reg* -quiet]] > 0)} {
#set_false_path -from [get_pins -hierarchical -filter {NAME =~ *wr_rst_i_reg/C}] -to [get_pins -hierarchical -filter {NAME =~ *d_out_reg/D}]
#wr_rst_rd_reg[*]/D}]
#set_false_path -from [get_pins -hierarchical -filter {NAME =~ *rd_rst_d3_reg/C}] -to [get_pins -hierarchical -filter {NAME =~ *d_out_reg/D}]
#}





# User Generated miscellaneous constraints 

current_instance -quiet
set_property HD.RECONFIGURABLE true [get_cells add_1]
set_property HD.RECONFIGURABLE true [get_cells comp_1]
set_property HD.RECONFIGURABLE true [get_cells dec_1]
set_property HD.RECONFIGURABLE true [get_cells div_1]
set_property HD.RECONFIGURABLE true [get_cells inc_1]
set_property HD.RECONFIGURABLE true [get_cells mod_1]
set_property HD.RECONFIGURABLE true [get_cells mul_1]
set_property HD.RECONFIGURABLE true [get_cells mux_1]
set_property HD.RECONFIGURABLE true [get_cells reg_1]
set_property HD.RECONFIGURABLE true [get_cells shl_1]
set_property HD.RECONFIGURABLE true [get_cells shr_1]
set_property HD.RECONFIGURABLE true [get_cells sub_1]

# User Generated physical constraints 

create_pblock pblock_add_1
add_cells_to_pblock [get_pblocks pblock_add_1] [get_cells -quiet [list add_1]]
resize_pblock [get_pblocks pblock_add_1] -add {SLICE_X26Y135:SLICE_X31Y149}
resize_pblock [get_pblocks pblock_add_1] -add {RAMB18_X2Y54:RAMB18_X2Y59}
resize_pblock [get_pblocks pblock_add_1] -add {RAMB36_X2Y27:RAMB36_X2Y29}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_add_1]
set_property SNAPPING_MODE ON [get_pblocks pblock_add_1]
create_pblock pblock_comp_1
add_cells_to_pblock [get_pblocks pblock_comp_1] [get_cells -quiet [list comp_1]]
resize_pblock [get_pblocks pblock_comp_1] -add {SLICE_X50Y139:SLICE_X55Y149}
resize_pblock [get_pblocks pblock_comp_1] -add {RAMB18_X3Y56:RAMB18_X3Y59}
resize_pblock [get_pblocks pblock_comp_1] -add {RAMB36_X3Y28:RAMB36_X3Y29}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_comp_1]
set_property SNAPPING_MODE ON [get_pblocks pblock_comp_1]
create_pblock pblock_dec_1
add_cells_to_pblock [get_pblocks pblock_dec_1] [get_cells -quiet [list dec_1]]
resize_pblock [get_pblocks pblock_dec_1] -add {SLICE_X80Y137:SLICE_X87Y149}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_dec_1]
set_property SNAPPING_MODE ON [get_pblocks pblock_dec_1]
create_pblock pblock_div_1
add_cells_to_pblock [get_pblocks pblock_div_1] [get_cells -quiet [list div_1]]
resize_pblock [get_pblocks pblock_div_1] -add {SLICE_X96Y137:SLICE_X103Y148}
resize_pblock [get_pblocks pblock_div_1] -add {DSP48_X4Y56:DSP48_X4Y57}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_div_1]
set_property SNAPPING_MODE ON [get_pblocks pblock_div_1]
create_pblock pblock_inc_1
add_cells_to_pblock [get_pblocks pblock_inc_1] [get_cells -quiet [list inc_1]]
resize_pblock [get_pblocks pblock_inc_1] -add {SLICE_X108Y139:SLICE_X113Y148}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_inc_1]
set_property SNAPPING_MODE ON [get_pblocks pblock_inc_1]
create_pblock pblock_mod_1
add_cells_to_pblock [get_pblocks pblock_mod_1] [get_cells -quiet [list mod_1]]
resize_pblock [get_pblocks pblock_mod_1] -add {SLICE_X38Y102:SLICE_X49Y115}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_mod_1]
set_property SNAPPING_MODE ON [get_pblocks pblock_mod_1]
create_pblock pblock_mul_1
add_cells_to_pblock [get_pblocks pblock_mul_1] [get_cells -quiet [list mul_1]]
resize_pblock [get_pblocks pblock_mul_1] -add {SLICE_X58Y102:SLICE_X67Y115}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_mul_1]
set_property SNAPPING_MODE ON [get_pblocks pblock_mul_1]
create_pblock pblock_mux_1
add_cells_to_pblock [get_pblocks pblock_mux_1] [get_cells -quiet [list mux_1]]
resize_pblock [get_pblocks pblock_mux_1] -add {SLICE_X90Y103:SLICE_X93Y113}
resize_pblock [get_pblocks pblock_mux_1] -add {RAMB18_X4Y42:RAMB18_X4Y43}
resize_pblock [get_pblocks pblock_mux_1] -add {RAMB36_X4Y21:RAMB36_X4Y21}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_mux_1]
set_property SNAPPING_MODE ON [get_pblocks pblock_mux_1]
create_pblock pblock_reg_1
add_cells_to_pblock [get_pblocks pblock_reg_1] [get_cells -quiet [list reg_1]]
resize_pblock [get_pblocks pblock_reg_1] -add {SLICE_X26Y84:SLICE_X35Y99}
resize_pblock [get_pblocks pblock_reg_1] -add {RAMB18_X2Y34:RAMB18_X2Y39}
resize_pblock [get_pblocks pblock_reg_1] -add {RAMB36_X2Y17:RAMB36_X2Y19}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_reg_1]
set_property SNAPPING_MODE ON [get_pblocks pblock_reg_1]
create_pblock pblock_shl_1
add_cells_to_pblock [get_pblocks pblock_shl_1] [get_cells -quiet [list shl_1]]
resize_pblock [get_pblocks pblock_shl_1] -add {SLICE_X0Y34:SLICE_X11Y48}
resize_pblock [get_pblocks pblock_shl_1] -add {RAMB18_X0Y14:RAMB18_X0Y17}
resize_pblock [get_pblocks pblock_shl_1] -add {RAMB36_X0Y7:RAMB36_X0Y8}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_shl_1]
set_property SNAPPING_MODE ON [get_pblocks pblock_shl_1]
create_pblock pblock_shr_1
add_cells_to_pblock [get_pblocks pblock_shr_1] [get_cells -quiet [list shr_1]]
resize_pblock [get_pblocks pblock_shr_1] -add {SLICE_X34Y0:SLICE_X47Y18}
resize_pblock [get_pblocks pblock_shr_1] -add {DSP48_X2Y0:DSP48_X2Y5}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_shr_1]
set_property SNAPPING_MODE ON [get_pblocks pblock_shr_1]
create_pblock pblock_sub_1
add_cells_to_pblock [get_pblocks pblock_sub_1] [get_cells -quiet [list sub_1]]
resize_pblock [get_pblocks pblock_sub_1] -add {SLICE_X50Y34:SLICE_X57Y50}
resize_pblock [get_pblocks pblock_sub_1] -add {RAMB18_X3Y14:RAMB18_X3Y19}
resize_pblock [get_pblocks pblock_sub_1] -add {RAMB36_X3Y7:RAMB36_X3Y9}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_sub_1]
set_property SNAPPING_MODE ON [get_pblocks pblock_sub_1]

# User Generated miscellaneous constraints 


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
