
####################################################################################
# Generated by Vivado 2017.4 built on 'Fri Dec 15 20:54:30 MST 2017' by 'xbuild'
# Command Used: write_xdc ./Sources/xdc/top_all.xdc
####################################################################################


####################################################################################
# Constraints from file : 'top_io.xdc'
####################################################################################


####################################################################################
# Generated by Vivado 2017.4 built on 'Fri Dec 15 20:54:30 MST 2017' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'design_1_processing_system7_0_0.xdc'
####################################################################################

############################################################################
##
##  Xilinx, Inc. 2006            www.xilinx.com
############################################################################
##  File name :       ps7_constraints.xdc
##
##  Details :     Constraints file
##                    FPGA family:       zynq
##                    FPGA:              xc7z020clg400-1
##                    Device Size:        xc7z020
##                    Package:            clg400
##                    Speedgrade:         -1
##
##
############################################################################
############################################################################
############################################################################
# Clock constraints                                                        #
############################################################################
#The clocks are asynchronous, user should constrain them appropriately.#


############################################################################
# I/O STANDARDS and Location Constraints                                   #
############################################################################

#  Enet 0 / mdio / MIO[53]
#  Enet 0 / mdc / MIO[52]
#  GPIO / gpio[51] / MIO[51]
#  GPIO / gpio[50] / MIO[50]
#  UART 1 / rx / MIO[49]
#  UART 1 / tx / MIO[48]
#  SD 0 / cd / MIO[47]
#  USB Reset / reset / MIO[46]
#  SD 0 / data[3] / MIO[45]
#  SD 0 / data[2] / MIO[44]
#  SD 0 / data[1] / MIO[43]
#  SD 0 / data[0] / MIO[42]
#  SD 0 / cmd / MIO[41]
#  SD 0 / clk / MIO[40]
#  USB 0 / data[7] / MIO[39]
#  USB 0 / data[6] / MIO[38]
#  USB 0 / data[5] / MIO[37]
#  USB 0 / clk / MIO[36]
#  USB 0 / data[3] / MIO[35]
#  USB 0 / data[2] / MIO[34]
#  USB 0 / data[1] / MIO[33]
#  USB 0 / data[0] / MIO[32]
#  USB 0 / nxt / MIO[31]
#  USB 0 / stp / MIO[30]
#  USB 0 / dir / MIO[29]
#  USB 0 / data[4] / MIO[28]
#  Enet 0 / rx_ctl / MIO[27]
#  Enet 0 / rxd[3] / MIO[26]
#  Enet 0 / rxd[2] / MIO[25]
#  Enet 0 / rxd[1] / MIO[24]
#  Enet 0 / rxd[0] / MIO[23]
#  Enet 0 / rx_clk / MIO[22]
#  Enet 0 / tx_ctl / MIO[21]
#  Enet 0 / txd[3] / MIO[20]
#  Enet 0 / txd[2] / MIO[19]
#  Enet 0 / txd[1] / MIO[18]
#  Enet 0 / txd[0] / MIO[17]
#  Enet 0 / tx_clk / MIO[16]
#  GPIO / gpio[15] / MIO[15]
#  GPIO / gpio[14] / MIO[14]
#  GPIO / gpio[13] / MIO[13]
#  GPIO / gpio[12] / MIO[12]
#  GPIO / gpio[11] / MIO[11]
#  GPIO / gpio[10] / MIO[10]
#  GPIO / gpio[9] / MIO[9]
#  Quad SPI Flash / qspi_fbclk / MIO[8]
#  GPIO / gpio[7] / MIO[7]
#  Quad SPI Flash / qspi0_sclk / MIO[6]
#  Quad SPI Flash / qspi0_io[3]/HOLD_B / MIO[5]
#  Quad SPI Flash / qspi0_io[2] / MIO[4]
#  Quad SPI Flash / qspi0_io[1] / MIO[3]
#  Quad SPI Flash / qspi0_io[0] / MIO[2]
#  Quad SPI Flash / qspi0_ss_b / MIO[1]
#  GPIO / gpio[0] / MIO[0]






# User Generated miscellaneous constraints 

set_property HD.RECONFIGURABLE true [get_cells bm]
set_property HD.RECONFIGURABLE true [get_cells dq1]
set_property HD.RECONFIGURABLE true [get_cells sha]

# User Generated physical constraints 

create_pblock pblock_sha
add_cells_to_pblock [get_pblocks pblock_sha] [get_cells -quiet [list sha]]
resize_pblock [get_pblocks pblock_sha] -add {SLICE_X26Y101:SLICE_X49Y149}
resize_pblock [get_pblocks pblock_sha] -add {DSP48_X2Y42:DSP48_X2Y59}
resize_pblock [get_pblocks pblock_sha] -add {RAMB18_X2Y42:RAMB18_X2Y59}
resize_pblock [get_pblocks pblock_sha] -add {RAMB36_X2Y21:RAMB36_X2Y29}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_sha]
set_property SNAPPING_MODE ON [get_pblocks pblock_sha]
create_pblock pblock_dq1
add_cells_to_pblock [get_pblocks pblock_dq1] [get_cells -quiet [list dq1]]
resize_pblock [get_pblocks pblock_dq1] -add {SLICE_X94Y51:SLICE_X113Y99}
resize_pblock [get_pblocks pblock_dq1] -add {DSP48_X4Y22:DSP48_X4Y39}
resize_pblock [get_pblocks pblock_dq1] -add {RAMB18_X5Y22:RAMB18_X5Y39}
resize_pblock [get_pblocks pblock_dq1] -add {RAMB36_X5Y11:RAMB36_X5Y19}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_dq1]
set_property SNAPPING_MODE ON [get_pblocks pblock_dq1]

# User Generated miscellaneous constraints 


# User Generated physical constraints 

create_pblock pblock_bm
add_cells_to_pblock [get_pblocks pblock_bm] [get_cells -quiet [list bm]]
resize_pblock [get_pblocks pblock_bm] -add {SLICE_X2Y0:SLICE_X49Y49}
resize_pblock [get_pblocks pblock_bm] -add {DSP48_X0Y0:DSP48_X2Y19}
resize_pblock [get_pblocks pblock_bm] -add {RAMB18_X0Y0:RAMB18_X2Y19}
resize_pblock [get_pblocks pblock_bm] -add {RAMB36_X0Y0:RAMB36_X2Y9}

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
