# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dakre/dpr_rt/hw/Sources/lab/axi_dma_ctrl/axi_dma_ctrl.xci
# IP: The module: 'axi_dma_ctrl' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/axi_dma_ctrl/axi_dma_ctrl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_ctrl'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/axi_dma_ctrl/axi_dma_ctrl.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/axi_dma_ctrl/axi_dma_ctrl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/dakre/dpr_rt/hw/Sources/lab/axi_dma_ctrl/axi_dma_ctrl.xci
# IP: The module: 'axi_dma_ctrl' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/axi_dma_ctrl/axi_dma_ctrl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/axi_dma_ctrl/axi_dma_ctrl.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/axi_dma_ctrl/axi_dma_ctrl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
