# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dakre/dpr_rt/hw/Sources/lab/prd/prd.xci
# IP: The module: 'prd' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/prd/prd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prd'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/prd/prd.xdc
# XDC: The top module name and the constraint reference have the same name: 'prd'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/dakre/dpr_rt/hw/Sources/lab/prd/prd.xci
# IP: The module: 'prd' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/prd/prd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prd'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/dakre/dpr_rt/hw/Sources/lab/prd/prd.xdc
# XDC: The top module name and the constraint reference have the same name: 'prd'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
